### ISSUE TITLE
`r` is not incrementing the read line pointer in a while loop

### ISSUE THREAD

**Issue by ghost** [dylanrenwick/Clam#1]
**TIO LINK**:
https://tio.run/##S85JzP3/v9ywoOj//4zUnJx8rvL8opwULkUQ@K9bBgA
**CODE**:
`w1pr`

I was attempting to make a cat program, and `r` wasn't incrementing the read line pointer. What am  I doing wrong here/is this a bug?

**Comment by dylanrenwick** [comment]
Yeah that's an issue with the `r` token, it increments at compile time, not runtime. I can fix that though

**Comment by ghost** [comment]
@dylanrenwick Thank you for the quick response! Is there any workaround to this in the meantime?

**Comment by ghost** [comment]
Oh wait, you fixed it. I'll wait for TIO to update it

**Comment by dylanrenwick** [comment]
You could create a variable such as `a*` that you increment each iteration.
Something like `=a*0w1pRia*`

Which would basically be

```
myVar = 0;
while(1) {
    console.log(arguments[myVar++]);
}
```

EDIT:

Golfier version: `=q0w1pRiq`

Which uses `q` as the varname instead of `myVar`
